version: 1.2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
platform:
- x86
- x64
environment:
  matrix:
  - platform: x86
    QTDIR: C:\Qt\5.7\msvc2015
    OUTNAME: Win32
  - platform: x64
    QTDIR: C:\Qt\5.7\msvc2015_64
    OUTNAME: x64
build:
  project: GloSC.sln
  verbosity: normal
after_build:
- cmd: 7z a GloSC_%platform%.zip TargetConfig.ini %APPVEYOR_BUILD_FOLDER%\\build\%OUTNAME%\%configuration%\* %APPVEYOR_BUILD_FOLDER%\\build\Win32Only\%configuration%\* %APPVEYOR_BUILD_FOLDER%\dependencies\SFML-2.4.1-$(platform)\\bin %APPVEYOR_BUILD_FOLDER%\dependencies\ViGEmUM\$(platform)\\bin
artifacts:
- path: GloSC_$(platform).zip
  name: GloSC_$(platform)
deploy:
- provider: GitHub
  auth_token:
    secure: IUk+TRaAfx7h7g+Ci3/srkt/ATkKp/Df6zSo1Fcf3OfW4yL0bPlKWbkVoDJZFRHdWK9yJsG+6dBUDYB7OePiINMc97nfr8EwfEU8ULmOp0o=
  artifact: /GLoSC_x..\.zip/
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master